#!/bin/sh
set -e

/usr/local/bin/docker-boot

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

# dont start php-fpm if supervisord is enabled
# to be changed for specific variable
if [ ! -z ${SUPERVISORD_PATH+x} ] && [ "$SUPERVISORD_PATH" != "" ]; then 
	tail -f /tmp/stdout.log
else
	$@ && tail -f /tmp/stdout.log
fi
