#!/bin/bash

### load boot bash scripts
for f in /usr/local/bin/*.sh; do
	/bin/bash -c $f
done

### load additional on-demand scripts
if [ ! -z ${PHP_BOOT_SCRIPTS+x} ] && [ "$PHP_BOOT_SCRIPTS" != "" ] ; then
	for f in /usr/local/bin/*.sh; do
		/bin/bash -c $f
	done
fi

### expose php version
echo
/usr/local/bin/php -v
