#!/bin/bash

echo "[`date +"%d-%b-%Y %T"`] PHP-FPM Docker container boot"

### load boot bash scripts
for f in /usr/local/bin/*.sh; do
	/bin/bash -c $f
done

### load additional on-demand scripts
if [ ! -z ${PHP_BOOT_SCRIPTS+x} ] && [ "$PHP_BOOT_SCRIPTS" != "" ]; then
	printf "env PHP_BOOT_SCRIPTS: "

	for f in ${PHP_BOOT_SCRIPTS}; do
		printf "$f, ";

		rm -f /usr/local/bin/${f##*/}
		cp $f /usr/local/bin/

		chmod +x /usr/local/bin/${f##*/}
	done

	echo

	for f in ${PHP_BOOT_SCRIPTS}; do
		/bin/bash -c /usr/local/bin/${f##*/}
	done
fi

### expose php version
echo
/usr/local/bin/php -v
